### ISSUE TITLE
Mismatch Error When Reloading Pre-trained Weights for Inference Testing

### ISSUE THREAD

**Issue by whoisfrankyang** [deep-symbolic-mathematics/Multimodal-Math-Pretraining#1]
Hi,

I am encountering a mismatch error while attempting to reload the pre-trained weights (SNIP-10dmax) for inference testing on the model. Despite following the installation instructions meticulously to set up the environment and packages, the error arises when executing the command:

!python /content/drive/MyDrive/LLM/Multimodal-Math-Pretraining-main/train.py --reload_model /content/drive/MyDrive/LLM/Multimodal-Math-Pretraining-main/weights/snip-10dmax.pth

to load the weights. The specific error message indicates a size mismatch in several layers:

RuntimeError: Error(s) in loading state_dict for LinearPointEmbedder:
    size mismatch for hidden_layers.0.weight: copying a param with shape torch.Size([2112, 2112]) from checkpoint, the shape in current model is torch.Size([384, 384]).
    size mismatch for hidden_layers.0.bias: copying a param with shape torch.Size([2112]) from checkpoint, the shape in current model is torch.Size([384]).
    size mismatch for fc.weight: copying a param with shape torch.Size([512, 2112]) from checkpoint, the shape in current model is torch.Size([512, 384]).

This issue leads me to question whether there might be a discrepancy between the pre-trained model weights provided and the current model architecture in the repository, or if there were any steps I may have overlooked during the setup process.

I would greatly appreciate any guidance or suggestions you could offer to resolve this mismatch issue. Thank you for your time and assistance.

**Comment by parshinsh** [comment]
@whoisfrankyang Thank you for reaching out and for your interest in the SNIP project!


After replicating the steps from the repository, I didn't encounter this error. 
Noticed that you're probably running the wrong command of 1d for loading 10d model. The parameters like `max_input_dimension` affects data generation, vocabulary size and thus, input embedding layers in the model architecture. To load `snip-10dmax.pth` model,  set `max_input_dimension 10` as suggested in the last line of [run_pretrain.sh](https://github.com/deep-symbolic-mathematics/Multimodal-Math-Pretraining/blob/main/run_pretrain.sh). Can you run this command and let me know if you still encounter the mismatch error? 

```python train.py --reload_model ./weights/snip-10dmax.pth --loss_type CLIP --dump_path ./dump --max_input_dimension 10 --latent_dim 512```

**Comment by whoisfrankyang** [comment]
This command worked!
After running this command, I noticed that it is still doing pre-training work based on the given checkpoint. In the paper, it says the model runs for about 220 epochs with 1000 iterations/epoch and batch size 256. Is the checkpoint snip-10dmax.pth the result of the model for running about 220 epochs? Since the training it still going on after I reload the checkpoint, would the training ever converge? And if so, do you have an estimation on how many epochs that will take. These information can give me a rough estimate on the training time. Thanks!

**Comment by parshinsh** [comment]
@whoisfrankyang Happy to hear that!
Yes, the released checkpoint is after about 200 epochs. If you continue training from there, you'll likely see minimal loss reduction, indicating near convergence.

Training time varies with your setup and task specifics. For reference on training times per epoch with our setup, you can check [App B](https://arxiv.org/pdf/2310.02227.pdf).

**Comment by whoisfrankyang** [comment]
@parshinsh  So from my understanding, there is not really a "convergence point" in this model where the training will just stop after that. The model can technically run to the max_epoch if we let it run.
